---
output:
  pdf_document: default
  word_document: default
  html_document: default
---

title: "Heart failure project"
author: "Amalawa O Ogbomo "Max""
date: "29/01/2021"
output: html_document


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(data.table)
library(tibble)
library(Hmisc)
library(tidyverse)
library(dplyr)
library(tidyr)
#import as csv file
Heart_failure<-read.csv("C:/Users/aoogb/Desktop/cleveland_heartdata.csv", stringsAsFactors = TRUE, header = FALSE)

for (i in names(Heart_failure)){
  colnames(Heart_failure) <- c("age","sex","cp","trestbps", "chol", "fbs","restecg", "thalach", "exang", "oldpeak", "slope", "ca","thal","num" )
}
Heart_failure
str(Heart_failure)
```


```{r}
#Check for special, missing , finite elements to make sure Data is clean by creating a function is.dirty,  if not we apply cleaning techniques 
# analysis and  prediction of  heart failure 
is.dirty<- function(n){ 
  if (is.numeric(n)) !is.finite(n) else is.na(n)}
sapply(Heart_failure, is.dirty)
## summarise and describe the data 
str(Heart_failure)
summary(Heart_failure)
describe(Heart_failure)
```



```{r}
## Restructure each column starting with the target column, column of interest 
Heart_failure$num
is.na(Heart_failure$num)<-Heart_failure$num!=0 
Heart_failure$num
mean(is.na(Heart_failure$num))
Heart_failure[is.na(Heart_failure)] = 1
Heart_failure$num
table(Heart_failure$num)
Heart_failure$num<-as.factor(Heart_failure$num)
```
```{r}
library(ISwR)
library(GGally)
library(cdata)
library(wrapr)
library(ggpubr)
library(ggrepel)
library(grDevices)
library(ggbiplot)
library(ggplot2)
ggplot(Heart_failure, 
       aes(x = num, 
           y = ..count.. / sum(..count..))) + 
  geom_bar() +
  geom_bar(fill = "#0073C2FF") +
  labs(x = "predicted number", 
       y = "Percentage of heart disease present or not", 
       title  = "absence or presence of heart disease") +
  scale_y_continuous(labels = scales::percent)

plotdata<-Heart_failure%>%
  dplyr::count(num) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
plotdata


ggplot(plotdata, 
       aes(x = reorder(num, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Healthy heart diagnosis 0 and heart failure diagnosis 1 ", 
       y = "Percentage of absence or presence of heart disease",
        title  = "% absence or presence of heart diesase")

#Heart_failure<-Heart_failure%>%dplyr::select(Heart_failure$num,everything())
```
```{r}
#melted boxplot view of data using reshape package in R
library("reshape2")
Heart_failure_long <- melt(Heart_failure, id = "num")                           
head(Heart_failure_long)
Heart_failure_long

##outlier detection using box plot 
library(ggplot2)
ggplot(Heart_failure_long, aes(x = variable, y = value, fill=factor(num))) +            
      geom_boxplot(width=0.5, alpha=5.0, varwidth=T)+
      stat_summary(fun.y=mean, geom="point", shape=25, size=2, color="white")+
      coord_flip()
# This melted-boxpot gives us an overview of our data where there are category variables , contineous or even we can see potential of outliers in thalach, age because of the young age red marker and trestbps 
```

```{r}
#feature age 
Heart_failure$age
summary(Heart_failure$age)
#Check for outliers
boxplot.stats(Heart_failure$age)$out

 #decribing the column
 describe(Heart_failure$age)
 ggplot()+
  geom_jitter(aes(num, age), data =Heart_failure , colour ="red", palette = c("#00AFBB", "#E7B800"), 
              position = position_jitter(width = 0.05)) +
  geom_point(data=Heart_failure,aes(x=num,ymin=age, ymax=age,y=age), width = 0.5)+
  ggtitle("Density plot of age")
 #Density plot age 
  density_plotage<-ggplot(Heart_failure, aes(x = age)) +
  geom_density(colour = "green", fill = "#56B4E9") +
  scale_x_continuous(name = "age",
                     breaks = seq(29,77, 5),
                     limits=c(18,100)) +
  scale_y_continuous(name = "Density") +
  ggtitle("Density plot of age") +
  theme(axis.line = element_line(size=1, colour = "black"))
 density_plotage
 #Test for normality 
shapiro.test(Heart_failure$age)# the null hypothesis for the shapiro.test is rejected and the alternate is accepted therefore transformation is needed 
# the null hypothesis for the Shapiro-Wilk test is that a variable is normally distributed in some population. A different way to say the same is that a variable's values are a simple random sample from a normal distribution.  
# can tell that it is slightly negatively skewed , which agrees with the normality test. Therefore we transform this column to follow a normal distribution.
# need for Transformation
 Heart_failure$age<-log(Heart_failure$age+1)
 Heart_failure$age
 summary(Heart_failure$age)
```

```{r}
Heart_failure$sex
summary(Heart_failure$sex)
table(Heart_failure$sex)
#chi sqaure test
Heart_failure$sex<-as.factor(Heart_failure$sex)

Heart_failure$sex<-as.factor(Heart_failure$sex)
summary(Heart_failure$sex)

sexdata<-Heart_failure %>%
  dplyr::count(sex) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
sexdata

ggplot(sexdata, 
       aes(x = reorder(sex, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "sex", 
       y = "Percentage", 
       title  = "Plot of sex")


ggboxplot(Heart_failure, x = "num", y = "sex", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "sex", xlab = "prediction of heart health")

ggplot(Heart_failure, 
       aes(x = sex, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))

# the chi square test, a non-parametric statistic to determine if there is any association 
# Create a data frame from the main data set.
sex_data<- data.frame(Heart_failure$sex,Heart_failure$num)

# Create a table with the needed variables.
sex_data = table(Heart_failure$sex,Heart_failure$num) 
print(sex_data)
sexchisq<-chisq.test(sex_data)
# Perform the Chi-Square test.
print(sexchisq)

sexchisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = 22.043, df = 1, p-value = 2.667e-06, If we assume predetermined level of significance to be 0.05 then we reject the null hypothesis.


sexchisq$observed
sexchisq$expected
round(sexchisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(sexchisq$observed−sexchisq$expected)/√sexchisq$observed , this is the literary explanation  we now do it in R program.
round(sexchisq$residuals, 3)
library(corrplot)
corrplot(sexchisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) 
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribsex=residuals^2/X-squared
#100*sexchisq$residuals^2/sexchisq$statistic in percentage 
#X-squared = sexchisq$statistic
contribsex<- 100*sexchisq$residuals^2/sexchisq$statistic
round(contribsex, 3)
corrplot(contribsex, is.cor = FALSE)
```


```{r}
Heart_failure$cp# chest pain type cp: chest pain type
       # -- Value 1: typical angina
        #-- Value 2: atypical angina
        #-- Value 3: non-anginal pain
       # -- Value 4: asymptomatic
# chest pain is a category of 4 types therefore we set the class cp to level of four. 
  is.na(Heart_failure$cp)<-Heart_failure$cp<1|Heart_failure$cp>4
  is.na(Heart_failure$cp)
  Heart_failure$cp 
  complete.cases(Heart_failure$cp)
  mean(is.na(Heart_failure$cp ))
  Heart_failure$cp<-as.factor(Heart_failure$cp)
  Heart_failure$cp 
  
  Heart_failure$cp<-as.factor(Heart_failure$cp)
summary(Heart_failure$cp)

cpdata<-Heart_failure %>%
  dplyr::count(cp) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
cpdata

ggplot(cpdata, 
       aes(x = reorder(cp, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "cp", 
       y = "Percentage", 
       title  = "Plot of cp")


ggboxplot(Heart_failure, x = "num", y = "cp", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "cp", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = cp, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))

# Create a data frame from the main data set.
cp_data<- data.frame(Heart_failure$cp,Heart_failure$num)

# Create a table with the needed variables.
cp_data = table(Heart_failure$cp,Heart_failure$num) 
print(cp_data)
cpchisq<-chisq.test(cp_data)
# Perform the Chi-Square test.
print(cpchisq)

cpchisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = X-squared = 81.816, df = 3, p-value < 2.2e-16, If we assume predetermined level of significance to be 0.05 then we reject the null hypothesis.


cpchisq$observed
cpchisq$expected
round(cpchisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(cpchisq$observed−cpchisq$expected)/√cpchisq$observed , this is the literary explanation  we now do it in R program.
round(cpchisq$residuals, 3)
library(corrplot)
corrplot(cpchisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of cp and column variables of num features
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribcp=residuals^2/X-squared
#100*cpchisq$residuals^2/cpchisq$statistic in percentage 
#X-squared = cpchisq$statistic
contribcp<- 100*cpchisq$residuals^2/cpchisq$statistic
round(contribcp, 3)
corrplot(contribcp, is.cor = FALSE)

  
```

```{r}
#(trestbps)   resting blood pressure (in mm Hg on admission to the 
     # hospital)normal blood pressure is considered to be between 90/60mmHg and 120/80mmHg
Heart_failure$trestbps<-as.numeric(Heart_failure$trestbps)

Heart_failure$trestbps
summary(Heart_failure$trestbps)
#Check for outliers
boxplot.stats(Heart_failure$trestbps)$out
summary(Heart_failure$trestbps)
ggplot()+
  geom_jitter(aes(num, trestbps), data =Heart_failure , colour ="red", palette = c("#00AFBB", "#E7B800"), 
              position = position_jitter(width = 0.05)) +
  geom_point(data=Heart_failure,aes(x=num,ymin=trestbps, ymax=trestbps,y=trestbps), width = 0.5)+
  ggtitle("Density plot of trestbps")
 #Density plot trestbps 


  density_plottrestbps<-ggplot(Heart_failure, aes(x = trestbps)) +
  geom_density(colour = "green", fill = "#56B4E9") +
  scale_x_continuous(name = "trestbps",
                     breaks = seq(94,200, 10),
                     limits=c(80,200)) +
  scale_y_continuous(name = "Density") +
  ggtitle("Density plot of resting blood pressure") +
  theme(axis.line = element_line(size=1, colour = "black"))
 density_plottrestbps
#Test for normality
shapiro.test(Heart_failure$trestbps)
# he null hypothesis for the Shapiro-Wilk test is that a variable is normally distributed in some population. A different way to say the same is that a variable's values are a simple random sample from a normal distribution. ... Well, p is basically the probability of finding our data if the null hypothesis is true
 
 # need for Transformation
 Heart_failure$trestbps<-log(Heart_failure$trestbps+1)
 
 Heart_failure$trestbps
 summary(Heart_failure$trestbps)
```


```{r}
     # -- 5. #12 (chol) serum cholestoral in mg/dl 
Heart_failure$chol
summary(Heart_failure$chol)
#Check for outliers
boxplot.stats(Heart_failure$chol)$out
ggplot()+
  geom_jitter(aes(num, chol), data =Heart_failure , colour ="red", palette = c("#00AFBB", "#E7B800"), 
              position = position_jitter(width = 0.05)) +
  geom_point(data=Heart_failure,aes(x=num,ymin=chol, ymax=chol,y=chol), width = 0.5)+
  ggtitle("Density plot of chol")
 #Density plot chol 


  density_plotchol<-ggplot(Heart_failure, aes(x = chol)) +
  geom_density(colour = "green", fill = "#56B4E9") +
  scale_x_continuous(name = "chol",
                     breaks = seq(100,564, 20),
                     limits=c(80,565)) +
  scale_y_continuous(name = "Density") +
  ggtitle("Density plot of resting blood pressure") +
  theme(axis.line = element_line(size=1, colour = "black"))
 density_plotchol
#Test for normality
shapiro.test(Heart_failure$chol)
# he null hypothesis for the Shapiro-Wilk test is that a variable is normally distributed in some population. A different way to say the same is that a variable's values are a simple random sample from a normal distribution. .
 
 # need for Transformation
 Heart_failure$chol<-log(Heart_failure$chol+1)
 
 Heart_failure$chol
 summary(Heart_failure$chol)
```

```{r}
     # -- 6. #16 (fbs)      (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false) 
Heart_failure$fbs
                        
Heart_failure$fbs<-as.factor(Heart_failure$fbs)
summary(Heart_failure$fbs)

fbsdata<-Heart_failure %>%
  dplyr::count(fbs) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
fbsdata

ggplot(fbsdata, 
       aes(x = reorder(fbs, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "fbs", 
       y = "Percentage", 
       title  = "Plot of fbs")


ggboxplot(Heart_failure, x = "num", y = "fbs", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "fbs", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = fbs, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))


# Create a data frame from the main data set.
fbs_data<- data.frame(Heart_failure$fbs,Heart_failure$num)

# Create a table with the needed variables.
fbs_data = table(Heart_failure$fbs,Heart_failure$num) 
print(fbs_data)
fbschisq<-chisq.test(fbs_data)
# Perform the Chi-Square test.
print(fbschisq)

fbschisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = 0.077095, df = 1, p-value = 0.7813 , If we assume predetermined level of significance to be 0.05 then we fail to reject the null hypothesis.


fbschisq$observed
fbschisq$expected
round(fbschisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(fbschisq$observed−fbschisq$expected)/√fbschisq$observed , this is the literary explanation  we now do it in R program.
round(fbschisq$residuals, 3)
library(corrplot)
corrplot(fbschisq$residuals, is.cor = FALSE)
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribfbs=residuals^2/X-squared
#100*fbschisq$residuals^2/fbschisq$statistic in percentage 
#X-squared = fbschisq$statistic
contribfbs<- 100*fbschisq$residuals^2/fbschisq$statistic
round(contribfbs, 3)
corrplot(contribfbs, is.cor = FALSE)

```

```{r}
Heart_failure$restecg
is.na(Heart_failure$restecg)<-Heart_failure$restecg<0|Heart_failure$restecg>2
complete.cases(Heart_failure$restecg)
mean(is.na(Heart_failure$restecg))
Heart_failure$restecg



      #  -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST 
      #              elevation or depression of > 0.05 mV)
      #  -- Value 2: showing probable or definite left ventricular hypertrophy
      #               by Estes' criteria
Heart_failure$restecg<-as.factor(Heart_failure$restecg)
summary(Heart_failure$restecg)

restecgdata<-Heart_failure %>%
  dplyr::count(restecg) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
restecgdata

ggplot(restecgdata, 
       aes(x = reorder(restecg, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "restecg", 
       y = "Percentage", 
       title  = "Plot of restecg")


ggboxplot(Heart_failure, x = "num", y = "restecg", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "restecg", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = restecg, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))


restecg_data<- data.frame(Heart_failure$restecg,Heart_failure$num)

# Create a table with the needed variables.
restecg_data = table(Heart_failure$restecg,Heart_failure$num) 
print(restecg_data)
restecgchisq<-chisq.test(restecg_data)
# Perform the Chi-Square test.
print(restecgchisq)

restecgchisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = 10.052, df = 2, p-value = 0.006567, If we assume predetermined level of significance to be 0.05 then we reject the null hypothesis.


restecgchisq$observed
restecgchisq$expected
round(restecgchisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(restecgchisq$observed−restecgchisq$expected)/√restecgchisq$observed , this is the literary explanation  we now do it in R program.
round(restecgchisq$residuals, 3)
library(corrplot)
corrplot(restecgchisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of restecg and column variables of target feature num
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribrestecg=residuals^2/X-squared
#100*restecgchisq$residuals^2/restecgchisq$statistic in percentage 
#X-squared = restecgchisq$statistic
contribrestecg<- 100*restecgchisq$residuals^2/restecgchisq$statistic
round(contribrestecg, 3)
corrplot(contribrestecg, is.cor = FALSE)
```

```{r}
      # -- 8. #32 (thalach)   maximum heart rate achieved
Heart_failure$thalach
summary(Heart_failure$thalach)
#Check for outliers
boxplot.stats(Heart_failure$thalach)$out

summary(Heart_failure$thalach)
ggplot()+
  geom_jitter(aes(num, thalach), data =Heart_failure , colour ="red", palette = c("#00AFBB", "#E7B800"), 
              position = position_jitter(width = 0.05)) +
  geom_point(data=Heart_failure,aes(x=num,ymin=thalach, ymax=thalach,y=thalach), width = 0.5)+
  ggtitle("Density plot of thalach")
 #Density plot thalach 


  density_plotthalach<-ggplot(Heart_failure, aes(x = thalach)) +
  geom_density(colour = "green", fill = "#56B4E9") +
  scale_x_continuous(name = "thalach",
                     breaks = seq(71,202,20),
                     limits=c(60,220)) +
  scale_y_continuous(name = "Density") +
  ggtitle("Density plot of maximum heart rate achieved") +
  theme(axis.line = element_line(size=1, colour = "black"))
 density_plotthalach
#Test for normality
shapiro.test(Heart_failure$thalach)
# he null hypothesis for the Shapiro-Wilk test is that a variable is normally distributed in some population. A different way to say the same is that a variable's values are a simple random sample from a normal distribution. ... Well, p is basically the probability of finding our data if the null hypothesis is true
 
 # need for Transformation
 Heart_failure$thalach<-log(Heart_failure$thalach+1)
 
Heart_failure$thalach
summary(Heart_failure$thalach)

```

```{r}
      # -- 9. #38 (exang)     exercise induced angina (1 = yes; 0 = no)
Heart_failure$exang
Heart_failure$exang<-as.factor(Heart_failure$exang)
summary(Heart_failure$exang)

exangdata<-Heart_failure %>%
  dplyr::count(exang) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
exangdata

ggplot(exangdata, 
       aes(x = reorder(exang, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "exang", 
       y = "Percentage", 
       title  = "Plot of exang")


ggboxplot(Heart_failure, x = "num", y = "exang", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "exang", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = exang, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))


# Create a data frame from the main data set.
exang_data<- data.frame(Heart_failure$exang,Heart_failure$num)

# Create a table with the needed variables.
exang_data = table(Heart_failure$exang,Heart_failure$num) 
print(exang_data)
exangchisq<-chisq.test(exang_data)
# Perform the Chi-Square test.
print(exangchisq)

exangchisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the exangtegoriexangl variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the exangtegoriexangl variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = X-squared = 54.686, df = 1, p-value = 1.414e-13, If we assume predetermined level of signifiexangnce to be 0.05 then we  reject the null hypothesis.


exangchisq$observed
exangchisq$expected
round(exangchisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to exanglculate the Chi-square statistic for each cell:

#r=(exangchisq$observed−exangchisq$expected)/√exangchisq$observed , this is the literary explanation  we now do it in R program.
round(exangchisq$residuals, 3)
library(corrplot)
corrplot(exangchisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of exang and column variables of target feature num 
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is exanglculated as follow:
#contribexang=residuals^2/X-squared
#100*exangchisq$residuals^2/exangchisq$statistic in percentage 
#X-squared = exangchisq$statistic
contribexang<- 100*exangchisq$residuals^2/exangchisq$statistic
round(contribexang, 3)
corrplot(contribexang, is.cor = FALSE)

```

```{r}
  
Heart_failure$oldpeak
summary(Heart_failure$oldpeak)

ggplot()+
  geom_jitter(aes(num, oldpeak), data =Heart_failure , colour ="red", palette = c("#00AFBB", "#E7B800"), 
              position = position_jitter(width = 0.05)) +
  geom_point(data=Heart_failure,aes(x=num,ymin=oldpeak, ymax=oldpeak,y=oldpeak), width = 0.5)+
  ggtitle("Density plot of oldpeak")
 #Density plot oldpeak 

#Check for outliers
boxplot.stats(Heart_failure$oldpeak)$out
  #6.2, 5.6, 4.2,  4.4 are identified as  outliers 
#Test for normality
shapiro.test(Heart_failure$oldpeak)
# he null hypothesis for the Shapiro-Wilk test is that a variable is normally distributed in some population. A different way to say the same is that a variable's values are a simple random sample from a normal distribution. ... Well, p is basically the probability of finding our data if the null hypothesis is true
 
  summary(Heart_failure$oldpeak)
 
 density_plotoldpeak<-ggplot(Heart_failure, aes(x = oldpeak)) +
  geom_density(colour = "green", fill = "#56B4E9") +
  scale_x_continuous(name = "oldpeak",
                     breaks = seq(0.0, 6.20, 0.1),
                     limits=c(-2.0,7.0)) +
  scale_y_continuous(name = "Density") +
  ggtitle("Density plot of resting blood pressure") +
  theme(axis.line = element_line(size=1, colour = "black"))
 density_plotoldpeak
 
 
 # need for Transformation
 Heart_failure$oldpeak<-log(Heart_failure$oldpeak+1)
 
 summary(Heart_failure$oldpeak)
```


```{r}
      # -- 11. #41 (slope)     slope: the slope of the peak exercise ST segment
Heart_failure$slope 
      #                        -- Value 1: upsloping
      #                         -- Value 2: flat
      #                         -- Value 3: downsloping
is.na(Heart_failure$slope)<-Heart_failure$slope<1|Heart_failure$slope>3
complete.cases(Heart_failure$slope)
mean(is.na(Heart_failure$slope))
Heart_failure$slope
#test for association
#check  for outliers
#check for normality, if it follows the parametric distribution
#Need for Transformation
#distribution visualization
Heart_failure$slope<-as.factor(Heart_failure$slope)
summary(Heart_failure$slope)

slopedata<-Heart_failure %>%
  dplyr::count(slope) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
slopedata

ggplot(slopedata, 
       aes(x = reorder(slope, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "slope", 
       y = "Percentage", 
       title  = "Plot of slope")


ggboxplot(Heart_failure, x = "num", y = "slope", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "slope", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = slope, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))

# Create a data frame from the main data set.
slope_data<- data.frame(Heart_failure$slope,Heart_failure$num)

# Create a table with the needed variables.
slope_data = table(Heart_failure$slope,Heart_failure$num) 
print(slope_data)
slopechisq<-chisq.test(slope_data)
# Perform the Chi-Square test.
print(slopechisq)

slopechisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = 45.785, df = 2, p-value = 1.143e-10, If we assume predetermined level of significance to be 0.05 then we  reject the null hypothesis.


slopechisq$observed
slopechisq$expected
round(slopechisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(slopechisq$observed−slopechisq$expected)/√slopechisq$observed , this is the literary explanation  we now do it in R program.
round(slopechisq$residuals, 3)
library(corrplot)
corrplot(slopechisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of slope and column variables heart failure diagnosis 
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribslope=residuals^2/X-squared
#100*slopechisq$residuals^2/slopechisq$statistic in percentage 
#X-squared = slopechisq$statistic
contribslope<- 100*slopechisq$residuals^2/slopechisq$statistic
round(contribslope, 3)
corrplot(contribslope, is.cor = FALSE)

```


```{r}
      # -- 12. #44 (ca)        number of major vessels (0-3) colored by flourosopy
Heart_failure$ca
Heart_failure$ca<-gsub("?",NA,Heart_failure$ca, fixed = TRUE)
is.na(Heart_failure$ca)<-Heart_failure$ca<0|Heart_failure$ca>3
complete.cases(Heart_failure$ca)
mean(is.na(Heart_failure$ca))
Heart_failure<-na.omit(Heart_failure)
Heart_failure$ca<-as.factor(Heart_failure$ca)
Heart_failure$ca

Heart_failure$ca<-as.factor(Heart_failure$ca)
summary(Heart_failure$ca)

cadata<-Heart_failure %>%
  dplyr::count(ca) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
cadata

ggplot(cadata, 
       aes(x = reorder(ca, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "ca", 
       y = "Percentage", 
       title  = "Plot of ca")


ggboxplot(Heart_failure, x = "num", y = "ca", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "ca", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = ca, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))

# Create a data frame from the main data set.
ca_data<- data.frame(Heart_failure$ca,Heart_failure$num)

# Create a table with the needed variables.
ca_data = table(Heart_failure$ca,Heart_failure$num) 
print(ca_data)
cachisq<-chisq.test(ca_data)
# Perform the Chi-Square test.
print(cachisq)

cachisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the categorical variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the categorical variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = 71.843, df = 3, p-value = 1.72e-15, If we assume predetermined level of significance to be 0.05 then we  reject the null hypothesis.


cachisq$observed
cachisq$expected
round(cachisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to calculate the Chi-square statistic for each cell:

#r=(cachisq$observed−cachisq$expected)/√cachisq$observed , this is the literary explanation  we now do it in R program.
round(cachisq$residuals, 3)
library(corrplot)
corrplot(cachisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of ca and column variables ofheart failure diagnosis
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is calculated as follow:
#contribca=residuals^2/X-squared
#100*cachisq$residuals^2/cachisq$statistic in percentage 
#X-squared = cachisq$statistic
contribca<- 100*cachisq$residuals^2/cachisq$statistic
round(contribca, 3)
corrplot(contribca, is.cor = FALSE)

```

```{r}
      # -- 13. #51 (thal)      3 = normal; 6 = fixed defect; 7 = reversable defect
Heart_failure$thal
Heart_failure$thal<-gsub("?",NA,Heart_failure$thal, fixed = TRUE)
is.na(Heart_failure$thal)<-Heart_failure$thal!=3&Heart_failure$thal!=6&Heart_failure$thal!=7
complete.cases(Heart_failure$thal)
mean(is.na(Heart_failure$thal))
# if we set the statistical significance at 0.05 for the mean , then we reject the null hypothesis 
Heart_failure<-na.omit(Heart_failure)
Heart_failure$thal
str(Heart_failure$thal)
      # -- 14. num: diagnosis of heart disease (angiographic disease status)
      #   -- Value 0: < 50% diameter narrowing
      #   -- Value 1: > 50% diameter narrowing
## Target column to be classified where , values 1 to 4 is set to 1 and value zero is set as zero.
Heart_failure$thal<-as.factor(Heart_failure$thal)
summary(Heart_failure$thal)

thaldata<-Heart_failure %>%
  dplyr::count(thal) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
thaldata

ggplot(thaldata, 
       aes(x = reorder(thal, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "thal", 
       y = "Percentage", 
       title  = "Plot of thal")


ggboxplot(Heart_failure, x = "num", y = "thal", 
          color = "num", palette = c("#00AFBB", "#E7B800"),
          order = c("0", "1"),
          ylab = "thal", xlab = "predicted heart condition")

ggplot(Heart_failure, 
       aes(x = thal, 
           fill = num)) + 
  geom_bar(position = position_dodge(preserve = "single"))

# Create a data frame from the main data set.
thal_data<- data.frame(Heart_failure$thal,Heart_failure$num)

# Create a table with the needed variables.
thal_data = table(Heart_failure$thal,Heart_failure$num) 
print(thal_data)
thalchisq<-chisq.test(thal_data)
# Perform the Chi-Square test.
print(thalchisq)

thalchisq$p.value
#Null hypothesis (H0): the row and the column variables of the contingency table are independent.
#Alternative hypothesis (H1): row and column variables are dependent
#Null hypothesis: There are no relationships between the thaltegorithall variables. If you know the value of one variable, it does not help you predict the value of another variable.
#Alternative hypothesis: There are relationships between the thaltegorithall variables. Knowing the value of one variable does help you predict the value of another variable.
#X-squared = X-squared = 82.46, df = 2, p-value < 2.2e-16, If we assume predetermined level of signifithalnce to be 0.05 then we reject the null hypothesis.


thalchisq$observed
thalchisq$expected
round(thalchisq$expected,2)
#If you want to know the most contributing cells to the total Chi-square score, you just have to thallculate the Chi-square statistic for each cell:

#r=(thalchisq$observed−thalchisq$expected)/√thalchisq$observed , this is the literary explanation  we now do it in R program.
round(thalchisq$residuals, 3)
library(corrplot)
corrplot(thalchisq$residuals, is.cor = FALSE)
#Positive residuals are in blue. Positive values in cells specify an attraction (positive association) between the corresponding row of thal and column variables of heart failure diagnosis
#In the image below, it’s evident that there are an association between the columns
#The contribution (in %) of a given cell to the total Chi-square score is thallculated as follow:
#contribthal=residuals^2/X-squared
#100*thalchisq$residuals^2/thalchisq$statistic in percentage 
#X-squared = thalchisq$statistic
contribthal<- 100*thalchisq$residuals^2/thalchisq$statistic
round(contribthal, 3)
#corrplot(contribthal, is.cor = FALSE)

```


```{r}
#convert data to numeric and target class to factor of 0 0r 1
describe(Heart_failure)
 summary(Heart_failure)
 Heart_failure[]<- lapply(Heart_failure, function(x) {
  if(!is.numeric(x)|is.integer(x)) as.numeric(as.character(x)) else x
 })
sapply(Heart_failure, class)
Heart_failure$num<-as.factor(Heart_failure$num) 
str(Heart_failure)
summary(Heart_failure)
table(Heart_failure$num)
```






```{r}
library(corrplot)
library(ggcorrplot)
str(Heart_failure)
  Heart_failure[]<-lapply(Heart_failure, function(x) {
  if(!is.numeric(x)|is.integer(x))as.numeric(as.character(x)) else x
 })
sapply(Heart_failure, class)

table(Heart_failure$num)
pairs(Heart_failure)
correlations=cor(Heart_failure,Heart_failure$num,method = "spearman")
correlations 
plot(correlations)
corrplot(correlations, number.cex =1, method = "circle", type = "full", tl.cex=.8,tl.col = "black")
Heart_failurematrix<-as.matrix(Heart_failure)
Corelationmatrix<-rcorr(Heart_failurematrix)
Corelationmatrix
# Extract the correlation coefficients
Corelationmatrix$r
correlationcoef<-as.data.frame(Corelationmatrix$r)
correlationcoef$num<-as.matrix(correlationcoef$num)
correlationcoef$num
# Extract p-values
Corelationmatrix$P 
Pvalue<-as.data.frame(Corelationmatrix$P )
Pvalue$num<-as.matrix(Pvalue$num)
Pvalue$num

correlation_correlationcoef_Pvalue<-cbind(correlations,correlationcoef$num,Pvalue$num) 
correlation_correlationcoef_Pvalue
correlation_correlationcoef_Pvalue<-data.frame(correlation_correlationcoef_Pvalue)
for (i in names(correlation_correlationcoef_Pvalue)){
  colnames(correlation_correlationcoef_Pvalue) <- c("correlations","correlationcoef$num","Pvalue$num")
}
correlation_correlationcoef_Pvalue
## visualize correlations and density plot and eclipes 
#install.packages("psych")
library(psych)
pairs.panels(Heart_failure[,-14], 
             method = "spearman", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE # show correlation ellipses
             )
str(Heart_failure)
```



```{r}

#Heat map correlation 
library(plotly)
library(heatmaply)
heatmaply_cor(
  cor(Heart_failure),
  xlab = "Heart_failure features", 
  ylab = "Heart_failure features",
  k_col = 2, 
  k_row = 2
)

heatmaply_cor(
  correlationcoef,
  node_type = "scatter",
  point_size_mat = -log10(Pvalue), 
  point_size_name = "-log10(Corelationmatrix$P)",
  label_names = c("x", "y", "Correlation")
)
#Feature selection
# ensure results are repeatable
set.seed(7)
# load the library
```

```{r}
 #it is important to rank our features with level of importance
library(mlbench)
library(caret)
# load the dataset
Heart_failure
# prepare training scheme
control <- trainControl(method="repeatedcv", number=10, repeats=3)
#train the model
model<-train(num~.,data=Heart_failure, trControl=control)
# estimate variable importance
importance <- varImp(model, scale=FALSE)
# summarize importance
print(importance)
# plot importance
plot(importance)
```
```{r}
#Principal Component Analysis 
library(modelr)
library(gridExtra)
library(devtools)
library(githubinstall)
library(dplyr)

Heart_failure
str(Heart_failure)
  Heart_failure[]<-lapply(Heart_failure, function(x) {
  if(!is.numeric(x)|is.integer(x))as.numeric(as.character(x)) else x
 })
sapply(Heart_failure, class)
str(Heart_failure)
# we remove the target column and store in a variable called  numR, 
numR<-select(Heart_failure, -14)
#summary(datairis)
str(numR)
head(numR)
pca.Heart_failure<-prcomp (numR, scale = TRUE)
pca.Heart_failure
#summary(pca.Heart_failure)
#rotation
pca.Heart_failure$rotation
pca.Heart_failure$rotation <- -pca.Heart_failure$rotation
pca.Heart_failure$rotation
pca.Heart_failure  # We can see from the code that the principal components have been rotated and are now negative values of the first principal components, all positive signs now negative and all negative signs now positive 
    #let us visualize the variance across the Principal components with a plot and it shows that there is high variance in the first and second principal component
plot(pca.Heart_failure)
  
pca.Heart_failure$x
pca.Heart_failure$x<- -pca.Heart_failure$x
pca.Heart_failure$x

# we find the standard deviation with the code below 
pca.Heart_failure$sdev
VE<-pca.Heart_failure$sdev^2
PVE <- VE / sum(VE)
round(PVE, 2)
PVE

# To be able to plot a scattered plot that involves num target feature  we have to column bind num(predicted diagnosis) back into the Principle components data 
pca.Heart_failure$x <- data.frame(pca.Heart_failure$x, num=Heart_failure$num)
                  
pca.Heart_failure$x$num<-as.factor(pca.Heart_failure$x$num)



#To plot a scatter plot of   PC1 vs. PC2, where data clusters corresponding to features combination are clearly marked using possibly an elipsoid
# first we bind back the pca.Heart_failure$num column 
ggplot(pca.Heart_failure$x,obs.scale = 1, var.scale = 1, groups = pca.Heart_failure$x.class, ellipse = TRUE, circle = F, ellipse.prob=0.75, aes(x=PC1, y=PC2, color=num))+ geom_point()
 
g <- ggbiplot(pca.Heart_failure, obs.scale = 1, var.scale = 1, groups = Heart_failure$num, ellipse = TRUE, circle = F, ellipse.prob=0.75, varname.size=3,
         var.axes=T)
#g <- g + scale_color_discrete(colors = 'num')
g <- g + theme(legend.direction = 'horizontal', legend.position = 'top')
print(g)

#Correlation between PCs.

pca.Heart_failure$x$num<-as.numeric(as.character(pca.Heart_failure$x$num))
correl=cor(pca.Heart_failure$x)
correlations
#Correlation plot.
corrplot(correl, order="hclust")
str(heart)
```





